name: Auto-merge PRs

# PRが作成・更新されたら自動実行
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Auto-merge PR into main
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
